---
# tasks file for OpenVPN
- name: Update Repositories
  become: yes
  apt:
    update_cache: yes

- name: Install Prerequisites
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - ca-certificates
      - wget
      - net-tools

- name: Download and install gpg key for the openvpn repository
  become: yes
  shell: wget -qO - https://as-repository.openvpn.net/as-repo-public.gpg | apt-key add -

- name: Install the openvpn repository
  become: yes
  shell: echo "deb http://as-repository.openvpn.net/as/debian bionic main">/etc/apt/sources.list.d/openvpn-as-repo.list

- name: Update the repositories and install the openvpn-as package
  become: yes
  apt:
    name: openvpn-as
    update_cache: yes

- name: Install Prerequisites
  become: yes
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - bind9
      - bind9utils
      - bind9-doc

- name: Create Bind automation directory
  become: yes
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - '/root/.bind_automate'

- name: Upload DNS forwarding configuration file
  become: yes
  copy:
    src: named.conf.options
    dest: /root/.bind_automate/named.conf.options

- name: Upload bind9 initialization script
  become: yes
  copy:
    src: bind_init.sh
    dest: /root/.bind_automate/bind_init.sh

- name: Change permissions on bind_init.sh
  become: yes
  file:
    path: /root/.bind_automate/bind_init.sh
    mode: "u+rwx"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Run Bind Initialization script
  become: yes
  command: /root/.bind_automate/bind_init.sh
  args:
    executable: /bin/bash
